### PR TITLE
fix: close inherited file descriptors in child process on Linux

### LINKED ISSUE #657: Leaking FDs: Close non-std FDs between pty_forkpty and pty_execvpe
## Environment details

- OS: Linux
- OS version: Linux 6.7
- node-pty version: The one bundled in VSCode, and I believe it still exists on master

## Issue description

Related to https://github.com/microsoft/vscode/issues/202558 .

Currently node-pty doesn't close unwanted fds before spawning the process in `pty_execvpe`. This caused the above issue where Node's open fd(s) accidentally leaks into the spawned process. Considering that very few spawned shell process are aware to the non-std fds, I doubt if this would ever be the desired behavior. 

To reduce the amount of surprise, I hope it could do something like https://github.com/facebook/folly/blob/main/folly/Subprocess.cpp#L559 to close all unwanted fds before spawning the shell.

---

EDIT from @Tyriar:

Lots more information in https://github.com/microsoft/node-pty/issues/710

### PR DESCRIPTION
**Pull request by Tyriar**
Prevents leaking file descriptors (pty master FDs, sockets, etc.) to child processes spawned via forkpty(). Uses close_range() syscall on Linux 5.9+, falling back to /proc/self/fd iteration, then brute force.

macOS already handles this via POSIX_SPAWN_CLOEXEC_DEFAULT flag.

Fixes #657
Part of microsoft/vscode#58814

### CODE REVIEW

File: src/unix/pty.cc [hunk 1]
```diff
@@ -110,6 +112,48 @@ struct ExitEvent {
...
+#if defined(__linux__)
+/**
+ * Close all file descriptors >= 3 to prevent FD leakage to child processes.
+ * Uses close_range() syscall on Linux 5.9+, falls back to /proc/self/fd iteration.
+ */
+static void
+pty_close_inherited_fds() {
+  // Try close_range() first (Linux 5.9+, glibc 2.34+)
+  #if defined(SYS_close_range)
+  if (syscall(SYS_close_range, 3, ~0U, 0) == 0) {
```
Comment (deepak1556) [inline src/unix/pty.cc]: We can let the exec call take care of closing

```suggestion
  if (syscall(SYS_close_range, 3, ~0U, CLOSE_RANGE_CLOEXEC) == 0) {
```

File: src/unix/pty.cc [hunk 2]
```diff
@@ -110,6 +112,48 @@ struct ExitEvent {
...
+    }
+    close(dirfd);
+  }
+
+  // Ultimate fallback: brute force (slow with high ulimit)
+  long max_fd = sysconf(_SC_OPEN_MAX);
+  if (max_fd < 0) max_fd = 1024;
+  for (int fd = 3; fd < max_fd; fd++) {
+    close(fd);
+  }
```
Comment (deepak1556) [inline src/unix/pty.cc]: We can mimic libuv https://github.com/libuv/libuv/blob/f420c2bd57ba79d21e1797324ed3ca18e8d92f89/src/unix/core.c#L800-L809 set cloexec flags on the fds and bail on the first error. The last call here to go over `_SC_OPEN_MAX` is really horrible for spawn performance.

```suggestion
  int fd;
  /* Set the CLOEXEC flag on all open descriptors. Unconditionally try the
   * first 16 file descriptors. After that, bail out after the first error.
   */
  for (fd = 3; ; fd++)
    if (SetCloseOnExec(fd) && fd > 15)
      break;
```

SetCloseOnExec would be as follows,

```c++
int SetCloseOnExec(int fd) {
  int flags = fcntl(fd, F_GETFD, 0);
  if (-1 == flags)
    return flags;
  if (flags & FD_CLOEXEC)
    return 0;
  return fcntl(fd, F_SETFD, flags | FD_CLOEXEC);
}
```
